### ISSUE TITLE
On schema import, throws error Unexpected key 'BillingModeSummary' found in params

### ISSUE THREAD

**Issue by praneetnadkar** [mifi/dynamodump#17]
dynamodump import-schema --region=us-west-2 --file=file --table=table_name --wait-for-active

On using the import command, it throws this error:

`UnexpectedParameter: Unexpected key 'BillingModeSummary' found in params
    at ParamValidator.fail (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\param_validator.js:77:14)
    at ParamValidator.validateMember (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\param_validator.js:88:21)
    at ParamValidator.validate (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\event_listeners.js:126:42)
    at Request.callListeners (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at callNextListener (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\event_listeners.js:86:9
    at finish (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\config.js:379:7)
    at C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\config.js:397:9
    at SharedIniFileCredentials.get (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\credentials.js:127:7)
    at getAsyncCredentials (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\config.js:391:24)
    at Config.getCredentials (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\config.js:411:9)
    at Request.VALIDATE_CREDENTIALS (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\event_listeners.js:81:26)
    at Request.callListeners (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\sequential_executor.js:102:18)
    at Request.emit (C:\Users\Praneet\AppData\Roaming\npm\node_modules\dynamodump\node_modules\aws-sdk\lib\sequential_executor.js:78:10)`

**Comment by mifi** [comment]
Try newest version now.

**Comment by praneetnadkar** [comment]
@mifi 
Works fine after the upgrade. Also, the schema export had a key called LastDecreaseDateTime in Indexes of the table. I commented that key, and then the import was fine. 
May be while exporting the schema, you need to ignore this key under indexes.

**Comment by mifi** [comment]
Could you show exactly where the key is located in the JSON? is it `index.ProvisionedThroughput.LastDecreaseDateTime` or `index.LastDecreaseDateTime`?
