### ISSUE TITLE
ETIMEDOUT, TCPConnectWrap.afterConnect

### ISSUE THREAD

**Issue by AlJohri** [mifi/dynamodump#8]
is this a throttling issue? or something else?

```
$ dynamodump export-data --table onondaga-e911-all-dev --region us-east-1
Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
```

```
$ dynamodump export-data --table onondaga-e911-closed-dev --region us-east-1                                                  
Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
```

**Comment by mifi** [comment]
reopen if still an issue
